version: '3'

services:
  api:
    build: .
    container_name: go-movies-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_movies
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
